# Generated by Django 4.1 on 2022-08-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_alter_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.TextField(choices=[]),
        ),
    ]
